In [9]:
# Regression Model:
'''
    Build a Model That Predicat the salary based on:
        --> city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size
'''

'\n    Build a Model That Predicat the salary based on:\n        --> city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size\n'

In [10]:
# Import Packages
import pandas as pd

In [34]:
# take just 100K rows
data = pd.read_csv("./data/job_market_dataset.csv")
data.head(2)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size,year,month
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large,2023,8
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large,2023,5

In [35]:
# Delete Features (year, month)
cp_data = data.drop(["year", "month"], axis=1)
cp_data.head(3)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large
2,Sweden,Stockholm,Software Engineer,Technology,10,258077.0,freelance,Master,Male,Enterprise

In [36]:
from sklearn.preprocessing import LabelEncoder

In [54]:
# Encoding The DataSet Features (country, city, field, employment_type, education_level, gender, company_size)
le = LabelEncoder()
features = ["country", "city", "occupation", "field", "employment_type", "education_level", "gender", "company_size"]
for feature in features:
    cp_data[feature] = le.fit_transform(cp_data[feature])
cp_data.head()

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size
0,17,21,8,5,16,359609.0,4,2,1,1
1,5,2,6,3,12,79059.0,3,3,1,1
2,16,17,10,6,10,258077.0,0,2,1,0
3,14,15,8,5,7,252282.0,3,2,0,1
4,20,11,2,6,4,330618.0,3,2,1,0

In [42]:
# Get X and y
X = cp_data.drop("salary", axis=1)
y = cp_data["salary"]

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
# Split Train Set, Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.head(2)

,country,city,occupation,field,years_of_experience,employment_type,education_level,gender,company_size
226114,7,10,3,6,19,0,1,2,1
435187,9,9,11,1,3,1,1,0,1

In [67]:
# from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [70]:
# Salary Normalisation Or Scaling
min_max_scal = MinMaxScaler(feature_range=(0, 1))
nd_data = min_max_scal.fit_transform(X=X_train, y=y_train)
df = pd.DataFrame(nd_data, columns=["country", "city", "occupation", "field", "years_of_experience", "employment_type", "education_level", "gender", "company_size"])
df

,country,city,occupation,field,years_of_experience,employment_type,education_level,gender,company_size
0,0.35,0.476190,0.272727,1.000000,0.76,0.00,0.333333,1.0,0.333333
1,0.45,0.428571,1.000000,0.166667,0.12,0.25,0.333333,0.0,0.333333
2,0.15,0.571429,0.727273,0.833333,0.00,0.00,0.333333,0.5,0.333333
3,0.70,0.714286,0.000000,1.000000,0.84,0.50,0.666667,1.0,0.666667
4,0.75,0.380952,0.000000,1.000000,0.00,0.00,0.333333,0.5,0.000000
...,...,...,...,...,...,...,...,...,...
349995,0.35,0.476190,1.000000,0.166667,0.12,0.75,0.333333,0.0,0.333333
349996,0.55,0.047619,0.545455,0.500000,0.80,0.50,0.333333,0.5,0.666667
349997,0.10,0.952381,0.909091,1.000000,0.08,0.50,0.333333,1.0,0.000000
349998,0.90,0.238095,0.545455,0.500000,0.52,0.25,0.333333,0.5,0.666667
349999,0.75,0.380952,0.181818,1.000000,0.80,1.00,0.000000,1.0,0.333333

In [71]:
from sklearn.ensemble import RandomForestRegressor

In [72]:
# Build a Model
model = RandomForestRegressor(n_estimators=100, oob_score=True)

In [73]:
# Fit Training Set with prediction result
model.fit(X_train, y_train)

RandomForestRegressor(oob_score=True)

In [ ]:
# Prediction
y_pred = model.predict(X_test)

array([275232.83683333, 134047.13483333, 263269.96341667, ...,
       295631.92333333, 135634.055     , 320338.06319048])

In [80]:
print(len(y_pred))

150000

In [49]:
# Get OOB (Out of Bug) Error
model.oob_score_

0.8780665546650054