In [2]:
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
# Load The Model
model = joblib.load("./my_model.pkl")
model

/home/abdellah/.local/lib/python3.12/site-packages/sklearn/base.py:463: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeRegressor from version 1.6.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/abdellah/.local/lib/python3.12/site-packages/sklearn/base.py:463: InconsistentVersionWarning: Trying to unpickle estimator RandomForestRegressor from version 1.6.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

RandomForestRegressor(oob_score=True)

In [12]:
# Get Test Set
X_train = pd.read_csv("./data/X_train.csv")
y_train = pd.read_csv("./data/y_train.csv")
X_test = pd.read_csv("./data/X_test.csv")
y_test = pd.read_csv("./data/y_test.csv")

# Get First Row
firstTwoRows = X_test.iloc[0:2]
firstTwoRows

,years_of_experience,education_level,gender,company_size,field_Business,field_Design,field_Finance,field_Human Resources,field_Marketing,field_Operations,...,occupation_Cloud Engineer,occupation_Data Analyst,occupation_Data Scientist,occupation_Financial Analyst,occupation_HR Analyst,occupation_Marketing Specialist,occupation_Operations Manager,occupation_Product Manager,occupation_Software Engineer,occupation_UX Designer
0,17,0,1,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,0,1,3,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

In [11]:
# Prediction
model.predict(firstTwoRows)

array([161084.09,  99619.86])

In [27]:
import pandas as pd
data = {"key1": "Switzerland","key2": 3,"key3": 4}
df = pd.DataFrame(list(data.items()), columns=["Key", "Values"])
print(df)

    Key       Values
0  key1  Switzerland
1  key2            3
2  key3            4

In [57]:
row_dict = {
    "country": "Switzerland",
    "city": "Zurich",
    "occupation": "Operations Manager",
    "field": "Operations",
    "years_of_experience": 16,
    "salary": 359609.0,
    "employment_type": "work_from_home",
    "education_level": "Master",
    "gender": "Male",
    "company_size": "Large"
}
cp_data = pd.DataFrame(data=[row_dict])
cp_data

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large

In [50]:
from sklearn.preprocessing import OneHotEncoder # for One Hot Encoding

In [55]:
# Mapping/Label Encoding This Varaibles
company_size_map = {'Large': 3, 'Enterprise': 2, 'Medium': 1, 'Small': 0}
cp_data["company_size"] = [company_size_map.get(v) for v in cp_data["company_size"]]

gender_map = {'Male': 0, 'Female': 1, 'Other': 2}
cp_data["gender"] = [gender_map.get(v) for v in cp_data["gender"]]

education_level_map = {'PhD': 3, 'Master': 2, 'Bachelor': 1, 'High School': 0}
cp_data["education_level"] = [education_level_map.get(v) for v in cp_data["education_level"]]

# One-Hot-Encoding
one_hot_encoder = OneHotEncoder()
cp_data = pd.get_dummies(cp_data, columns=["field", "employment_type", "city", "country", "occupation"])
cp_data.head(3)

,years_of_experience,salary,education_level,gender,company_size,field_Operations,employment_type_work_from_home,city_Zurich,country_Switzerland,occupation_Operations Manager
0,16,359609.0,2,0,3,True,True,True,True,True

In [83]:
# Add More Columns
all_features = model.feature_names_in_
for f in all_features:
    if (cp_data.get(f) is None):
        cp_data[f] = False
cp_data.columns

Index(['country', 'city', 'occupation', 'field', 'years_of_experience',
       'salary', 'employment_type', 'education_level', 'gender',
       'company_size', 'field_Business', 'field_Design', 'field_Finance',
       'field_Human Resources', 'field_Marketing', 'field_Operations',
       'field_Technology', 'employment_type_freelance',
       'employment_type_full_time', 'employment_type_internship',
       'employment_type_part_time', 'employment_type_work_from_home',
       'city_Amsterdam', 'city_Auckland', 'city_Bangalore', 'city_Berlin',
       'city_Cape Town', 'city_Dubai', 'city_Dublin', 'city_London',
       'city_Madrid', 'city_Mexico City', 'city_Milan', 'city_New York',
       'city_Paris', 'city_San Francisco', 'city_Sao Paulo', 'city_Seoul',
       'city_Singapore', 'city_Stockholm', 'city_Sydney', 'city_Tokyo',
       'city_Toronto', 'city_Zurich', 'country_Australia', 'country_Brazil',
       'country_Canada', 'country_France', 'country_Germany', 'country_India',
       'country_Ireland', 'country_Italy', 'country_Japan', 'country_Mexico',
       'country_Netherlands', 'country_New Zealand', 'country_Singapore',
       'country_South Africa', 'country_South Korea', 'country_Spain',
       'country_Sweden', 'country_Switzerland', 'country_United Arab Emirates',
       'country_United Kingdom', 'country_United States',
       'occupation_AI Engineer', 'occupation_Business Analyst',
       'occupation_Cloud Engineer', 'occupation_Data Analyst',
       'occupation_Data Scientist', 'occupation_Financial Analyst',
       'occupation_HR Analyst', 'occupation_Marketing Specialist',
       'occupation_Operations Manager', 'occupation_Product Manager',
       'occupation_Software Engineer', 'occupation_UX Designer'],
      dtype='object')

In [79]:
model.predict(cp_data)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- city
- country
- employment_type
- field
- occupation
- ...

In [70]:
print(cp_data.get("XY"))

None