In [ ]:
# Regression Model:
'''
    Build a Model That Predicat the salary based on:
        --> city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size
'''

In [35]:
# Import Packages
import pandas as pd

In [16]:
data = pd.read_csv("./data/job_market_dataset.csv")
data.head(2)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size,year,month
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large,2023,8
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large,2023,5

In [22]:
# Delete Features (year, month)
cp_data = data.drop(["year", "month"], axis=1)
cp_data.head(3)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large
2,Sweden,Stockholm,Software Engineer,Technology,10,258077.0,freelance,Master,Male,Enterprise

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [36]:
# Encoding The DataSet Features (country, city, field, employment_type, education_level, gender, company_size)
le = LabelEncoder()
cp_data["country"] = le.fit_transform(cp_data["country"])
cp_data["city"] = le.fit_transform(cp_data["city"])
cp_data["occupation"] = le.fit_transform(cp_data["occupation"])
cp_data["field"] = le.fit_transform(cp_data["field"])
cp_data["employment_type"] = le.fit_transform(cp_data["employment_type"])
cp_data["education_level"] = le.fit_transform(cp_data["education_level"])
cp_data["gender"] = le.fit_transform(cp_data["gender"])
cp_data["company_size"] = le.fit_transform(cp_data["company_size"])
cp_data.head()

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size
0,17,21,8,5,16,359609.0,4,2,1,1
1,5,2,6,3,12,79059.0,3,3,1,1
2,16,17,10,6,10,258077.0,0,2,1,0
3,14,15,8,5,7,252282.0,3,2,0,1
4,20,11,2,6,4,330618.0,3,2,1,0

In [45]:
# Get X and y
X = cp_data.drop("salary", axis=1)
y = cp_data["salary"]

In [ ]:
from sklearn.model_selection import train_test_split

In [42]:
# Split Train Set, Test Set
X_train, y_train, X_test, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.head(3)

,country,city,occupation,field,years_of_experience,employment_type,education_level,gender,company_size
226114,7,10,3,6,19,0,1,2,1
435187,9,9,11,1,3,1,1,0,1
294452,3,12,8,5,0,0,1,1,1