#### Description:

In [ ]:
'''
    I aim to Build a Model That Predicat the salary based on:
        (city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size)
'''

'\n    I aim to Build a Model That Predicat the salary based on:\n        (city, occupation, field, years_of_experience, employment_type, education_level, gender, company_size)\n'

#### Import Data and Select Features

In [2]:
# Import Packages
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')
%ls drive/MyDrive/job_market_dataset.csv

data = pd.read_csv("drive/MyDrive/job_market_dataset.csv")
# data = pd.read_csv("./data/job_market_dataset.csv")
data.head(2)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
drive/MyDrive/job_market_dataset.csv

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size,year,month
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large,2023,8
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large,2023,5

In [4]:
# Delete Features (year, month)
cp_data = data.drop(["year", "month"], axis=1)
cp_data = cp_data.iloc[:100000] # take just 100K
cp_data.head(4)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large
2,Sweden,Stockholm,Software Engineer,Technology,10,258077.0,freelance,Master,Male,Enterprise
3,South Korea,Seoul,Operations Manager,Operations,7,252282.0,part_time,Master,Female,Large

#### Feature Encoding

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.preprocessing import LabelEncoder # for Mapping / Label Encoder
from sklearn.preprocessing import OneHotEncoder # for One Hot Encoding

In [7]:
# Mapping/Label Encoding This Varaibles
company_size_map = {'Large': 3, 'Enterprise': 2, 'Medium': 1, 'Small': 0}
cp_data["company_size"] = [company_size_map[v] for v in cp_data["company_size"]]

gender_map = {'Male': 0, 'Female': 1, 'Other': 2}
cp_data["gender"] = [gender_map[v] for v in cp_data["gender"]]

education_level_map = {'PhD': 3, 'Master': 2, 'Bachelor': 1, 'High School': 0}
cp_data["education_level"] = [education_level_map[v] for v in cp_data["education_level"]]

# One-Hot-Encoding
one_hot_encoder = OneHotEncoder()
cp_data = pd.get_dummies(cp_data, columns=["field", "employment_type", "city", "country", "occupation"])
cp_data.head(3)

,years_of_experience,salary,education_level,gender,company_size,field_Business,field_Design,field_Finance,field_Human Resources,field_Marketing,...,occupation_Cloud Engineer,occupation_Data Analyst,occupation_Data Scientist,occupation_Financial Analyst,occupation_HR Analyst,occupation_Marketing Specialist,occupation_Operations Manager,occupation_Product Manager,occupation_Software Engineer,occupation_UX Designer
0,16,359609.0,2,0,3,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,12,79059.0,3,0,3,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,10,258077.0,2,0,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

#### Split Data

In [8]:
# Get X and y
X = cp_data.drop("salary", axis=1)
y = cp_data["salary"]

In [9]:
# Split Train Set, Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.head(3)

,years_of_experience,education_level,gender,company_size,field_Business,field_Design,field_Finance,field_Human Resources,field_Marketing,field_Operations,...,occupation_Cloud Engineer,occupation_Data Analyst,occupation_Data Scientist,occupation_Financial Analyst,occupation_HR Analyst,occupation_Marketing Specialist,occupation_Operations Manager,occupation_Product Manager,occupation_Software Engineer,occupation_UX Designer
76513,20,0,0,2,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
60406,20,2,0,0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
27322,15,1,1,1,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False

In [10]:
# Save Test Set as CSV File
X_test.to_csv("./x_test_set.csv", index=False)
y_test.to_csv("./y_test_set.csv", index=False)

#### Model Building (Random Forest)

In [11]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
# Build a Model
model = RandomForestRegressor(oob_score=True)

In [13]:
# Fit Training Set with prediction result
model.fit(X_train, y_train)

RandomForestRegressor(oob_score=True)

#### Save Model As PKL file

In [14]:
import joblib

In [15]:
# Save Model
joblib.dump(model, 'my_model.pkl')
print("Model saved successfully!")

Model saved successfully!

In [17]:
# Save Model --> PKL file in Google Drive
!mv my_model.pkl drive/MyDrive/git_projects/